#! /bin/sh
# script to compile C programs that are linked 
# against Fortran libraries
# last modified 7 Jun 11 th

args=
objs=
ldflags=
fldflags=
compileonly=

cc="${REALCC:-cc}"
cxx="${REALCXX:-c++}"
[ `basename $0` = f++ ] && cc="$cxx"

while [ $# -gt 0 ] ; do
  case "$1" in
  -arch)
	shift
	;;
  -st | -b32 | -b64)
	;;
  -[Ll]* | -Wl*)
	ldflags="$ldflags \"$1\""
	;;
  *.tm.o)
	objs="\"$1\" $objs"
	;;
  *.a | *.o | *.so)
	objs="$objs \"$1\""
	;;
  -Wno-long-double)
	# mcc adds this on Macs & gcc 4 doesn't like it
	;;
  *.cc)
	args="$args \"$1\""
	cc="$cxx"
	;;
  -c)
	compileonly="-c"
	;;
  -o)
	args="$args -o \"$2\""
	shift
	;;
  *)
	args="$args \"$1\""
	;;
  esac
  shift
done

eval "set -x ; $cc $args ${compileonly:-$objs $ldflags $fldflags}"

