#! /bin/sh
# script to compile C programs that are linked 
# against Fortran libraries
# last modified 25 Aug 14 th

args=
compileonly=
objs=
ldflags=
fldflags=

cc="${REALCC:-cc}"
cxx="${REALCXX:-c++}"
test `basename $0 .in` = f++ && cc="$cxx"

while test $# -gt 0 ; do
  case "$1" in
  -st | -b32 | -b64)
	;; # ignore mcc-specific flags
  -arch)
	shift
	;;
  -lstdc++)
	cc="$cxx"
	;; # or else -static-libstdc++ has no effect
  -Wno-long-double)
	;; # mcc adds this on Macs & gcc 4 doesn't like it
  -L*CompilerAdditions*)
	ldflags="$ldflags '$1'"
	mldir=`echo "$1" | sed '
	  s/^-L//
	  s/Links.MathLink.DeveloperKit/Libraries/
	  s/CompilerAdditions.*$//'`
	test -f "$mldir/libuuid.a" && fldflags="$fldflags '$mldir/libuuid.a'"
	;;
  -[Ll]* | -Wl*)
	ldflags="$ldflags '$1'"
	;;
  *.tm.o)
	objs="'$1' $objs"
	;;
  *.a | *.o | *.so)
	objs="$objs '$1'"
	;;
  *.cc)
	args="$args '$1'"
	cc="$cxx"
	;;
  -c)
	compileonly="-c"
	;;
  -o)
	args="$args -o '$2'"
	shift
	;;
  *)
	args="$args '$1'"
	;;
  esac
  shift
done

eval "set -x ; exec $cc $args ${compileonly:-$objs $ldflags $fldflags}"

